# Generated by Django 5.1.2 on 2024-10-29 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='creaated_at',
            new_name='created_at',
        ),
    ]
